version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  airflow:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 8001:8080
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./airflow/plugins:/usr/local/airflow/plugins
      - logs:/usr/local/airflow/logs

volumes:
  pgdata:
  logs:
